### PR TITLE
[Testing] Added webservices API tests to drone

### PR DESCRIPTION
**Pull request by yvesh**
@wilsonge you need to update from upstream branch and fix your code style. :)

### Summary of Changes

Adds API tests to this repo.

### Testing Instructions

Check Drone

### Expected result

We have api tests.

### Actual result

We have no api tests.

### CODE REVIEW

**Comment by rdeutz** [comment]
expected that drone fails here?

**Comment by wilsonge** [comment]
It's possible? Me and Yves had a test for a bug that required https://github.com/joomla/joomla-cms/pull/20431 and https://github.com/joomla-projects/gsoc18_webservices/pull/63 - but don't know if they made it into the repo

**Comment by yvesh** [comment]
Looks like i need to change codeception.yml after install run.. working on it :-)

**Comment by yvesh** [comment]
Okay fixed, green now (with 2 skipped tests that needs fixing in the API @wilsonge)

**Comment by wilsonge** [comment]
I just updated upstream again (which fixed the two broken tests) and unskipped the two broken ones. Somehow managed to make things fail. Isn't this password https://github.com/joomla/test-api/blob/4.0-dev/tests/api/contentCest.php#L27 supposed to be `admin` not `123`?

**Comment by yvesh** [comment]
@wilsonge yep fixed that now and restarted drone.. Should be green now.. Need to make the credentials a setting..

**Comment by wilsonge** [comment]
Nope. 404. Are we actually installing any sample data? If not I guess 404 makes sense as there will be no articles

**Comment by puneet0191** [comment]
not installing any Sample Data, so 404 makes sense

**Comment by wilsonge** [comment]
OK I've skipped that test for now - we can figure that out - maybe create the article before we get it

**Pull request merged**
