### PR TITLE
Added entry point of the API project

### PR DESCRIPTION
**Pull request by muhakh**
Added the entry point for Joomla webservices project which calls for the api app

### CODE REVIEW

**Review by cokencorn — COMMENTED** [review]
We can add the API library path into defines.

**Comment by yvesh** [comment]
Is there any reason you are not using the include files from joomla cms itself? (Like defines or framework.php)

**Comment by muhakh** [comment]
@yvesh We need defines for the api path and we need framework for our own Error handling

**Comment by mbabker** [comment]
> Is there any reason you are not using the include files from joomla cms itself? (Like defines or framework.php)

This is its own application entry point (similar to https://github.com/joomla/downloads.joomla.org/tree/master/api or the 3 apps in the main repo now).  Each app has its own bootstrap process, so this is fine.

**Pull request merged**
